---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/subjects":
    get:
      summary: subjects list
      tags:
      - Subjects
      responses:
        '200':
          description: Successful
        '204':
          description: No subjects
    post:
      summary: create a subject
      tags:
      - Subjects
      parameters: []
      responses:
        '201':
          description: Subject created
        '400':
          description: Bad Request
        '422':
          description: Invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: Subject title
                body:
                  type: string
                  description: Subject body
              required:
              - title
              - body
  "/api/v1/subjects/{id}":
    parameters:
    - name: id
      in: path
      required: true
      description: Subject ID
      schema:
        type: integer
    get:
      summary: show a subject
      tags:
      - Subjects
      responses:
        '200':
          description: Successful
        '404':
          description: Subject not found
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: 45dfbd071387.ngrok.app
